### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by martmalo** [mwolosewicz/esp-idf-mqtt#1]
Hey, I'm using esp idf v5.2 and encountered some issues while building my project.

`In file included from /Users/martmalo/esp/se_esp32c3_v1/components/mqtt_manager/mqtt_manager.c:8:
/Users/martmalo/esp/se_esp32c3_v1/components/mqtt_manager/mqtt_manager.c: In function 'mqtt_manager_subscribe':
/Users/martmalo/esp/esp-idf-v5.2/components/mqtt/esp-mqtt/include/mqtt_client.h:464:84: error: '_Generic' selector of type 'const char *' is not compatible with any association
  464 | #define esp_mqtt_client_subscribe(client_handle, topic_type, qos_or_size) _Generic((topic_type), \
      |                                                                                                 ^
/Users/martmalo/esp/se_esp32c3_v1/components/mqtt_manager/mqtt_manager.c:211:7: note: in expansion of macro 'esp_mqtt_client_subscribe'
  211 |       esp_mqtt_client_subscribe(s_client, topic, qos);`
  
  Do you know what is causing this issue?
  
  Thanks

**Comment by martmalo** [comment]
Fixed it by removing const from const char * in parameters of your mqtt_manager_subscribe function.

**Comment by mwolosewicz** [comment]
Thanks for pointing this up. Will push the fix.
